version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app_net

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_net

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 admin admin123;
      mc mb local/public --ignore-existing;
      mc anonymous set download local/public;
      echo '✅ Bucket public criado e liberado!';
      exit 0;
      "
    networks:
      - app_net

volumes:
  redis_data:
  minio_data:

networks:
  app_net:
    driver: bridge
